- id: job-log-ui.png
  workspace: examples/docs_snippets/docs_snippets/concepts/logging/builtin_logger.py
  steps:
    - run the job
    - navigate to the run page
  vetted: false

- id: job-ui-error.png
  workspace: examples/docs_snippets/docs_snippets/concepts/logging/builtin_logger.py
  steps:
    - run the job
    - navigate to the run page
  vetted: false

- id: job-ui-filter.png
  workspace: examples/docs_snippets/docs_snippets/concepts/logging/builtin_logger.py
  steps:
    - run the job
    - navigate to the run page
  vetted: false
