FROM python:3.10-slim

RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app

RUN pip install \
    dagster \
    dagster-postgres

    # Add repository code

COPY  defs.py  /opt/dagster/app/

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
